// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>XmlFormat</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>True</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>True</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>True</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace XmlFormat
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Text;
    using System.Collections.Generic;
    using System.Runtime.Serialization;


    #region Base entity class

    #endregion

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/XmlPartyInvites.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/XmlPartyInvites.xsd", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "XmlParty", Namespace = "http://tempuri.org/XmlPartyInvites.xsd")]
    public partial class XmlParty : XmlPartyBase<XmlParty>
    {


        private List<XmlPartyParty> partyField;

        [System.Xml.Serialization.XmlElementAttribute("Party", Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<XmlPartyParty> Party
        {
            get
            {
                return this.partyField;
            }
            set
            {
                this.partyField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/XmlPartyInvites.xsd")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "XmlPartyParty", Namespace = "http://tempuri.org/XmlPartyInvites.xsd")]
    public partial class XmlPartyParty : XmlPartyBase<XmlPartyParty>
    {


        private string messageField;


        private List<attendeeType> inviteField;


        private string idField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id { get; set; }


        [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Attendee", IsNullable = false)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<attendeeType> Invite
        {
            get
            {
                return this.inviteField;
            }
            set
            {
                this.inviteField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/XmlPartyInvites.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/XmlPartyInvites.xsd", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "attendeeType", Namespace = "http://tempuri.org/XmlPartyInvites.xsd")]
    public partial class attendeeType : XmlPartyBase<attendeeType>
    {

        private object itemField;
        private string idField;

        [System.Xml.Serialization.XmlElementAttribute("SmokeSignal", typeof(attendeeTypeSmokeSignal), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("SnailMail", typeof(postageType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("TelephoneCall", typeof(string), Order = 0)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Item { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/XmlPartyInvites.xsd")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "attendeeTypeSmokeSignal", Namespace = "http://tempuri.org/XmlPartyInvites.xsd")]
    public partial class attendeeTypeSmokeSignal : XmlPartyBase<attendeeTypeSmokeSignal>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/XmlPartyInvites.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/XmlPartyInvites.xsd", IsNullable = true)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "postageType", Namespace = "http://tempuri.org/XmlPartyInvites.xsd")]
    public partial class postageType : XmlPartyBase<postageType>
    {


        private string valueField;

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value { get; set; }

        private postageTypeClass classField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public postageTypeClass @class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/XmlPartyInvites.xsd")]
    public enum postageTypeClass
    {

        /// <remarks/>
        FirstClass,

        /// <remarks/>
        SecondClass,

        /// <remarks/>
        HandDelivered,
    }
}
